let productsDb = [
    {
        id: 1,
        title : 'headphone item',
        desc : 'With these headphones, you can enjoy the full-bodied audio',
        size : 'large' ,
        imageUrl : 'images/headphone.webp',
        qty:1,
        IsMe : 'f',
    },
    {
        id: 2,
        title : 'glasses item',
        desc : 'With these headphones, you can enjoy the full-bodied audio',
        size : 'large' ,
        imageUrl : 'images/eye..jpg',
        qty:1,
        IsMe : 'f',
    } ,
    {
        id: 3,
        title : 'wristwatch item',
        desc : 'With these headphones, you can enjoy the full-bodied audio',
        size : 'large' ,
        imageUrl : 'images/wristwatch.jpg',
        qty:1,
        IsMe : 'f',
    } ,
    {
        id: 4,
        title : 'laptop item',
        desc : 'With these headphones, you can enjoy the full-bodied audio',
        size : 'large' ,
        imageUrl : 'images/lap.jfif',
        qty:1,
        IsMe : 'f',
    },
]
